"""Glossa's backend. It exists to serve the data, and for no other reason.

The app itself is a static React SPA and needs no server at all. What it needs is for
its ~110MB of generated JSON to live somewhere a code deploy cannot destroy.

Until now that data sat in ``public/data/`` → ``dist/data/`` → ``frontend/data/`` on the
server. Three facts made that a loaded gun:

  1. ``public/data/*`` is gitignored — it is generated by ``data-prep``, not committed.
  2. A frontend directory is shipped with ``rsync --delete``.
  3. Therefore a deploy from any clean checkout would have mirrored an EMPTY data
     directory over the server's and erased all 110MB. The only reason it never happened
     is that glossa was deployed by a bespoke script that nobody else ever ran.

So the data moved out to ``~/.local/share/glossa/data/`` — outside the deploy-managed
tree, shipped by its own verb (``deploy.py cmd-push-data --app glossa``), never mirrored
and never deleted. This module is what puts it back on the wire, at ``/api/glossa/data/``.

Why ``StaticFiles`` and not a hand-rolled handler: it gets conditional requests, ETags
and range support right, and this is 3000 files of static JSON — precisely its job.
"""

import os
from pathlib import Path

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

#: Point this at another directory to relocate the data (tests, a second checkout, a
#: machine that keeps it on an external disk). Mirrored by `dataRoot()` in vite.config.ts.
DATA_DIR_ENV = "GLOSSA_APP_DATA_DIR"

#: Mounted relative to the app, so the public URL is /api/glossa/data/...
#: `.env` in this repo names the same path for the frontend. They must agree.
DATA_ROUTE = "data"

app = FastAPI(title="Glossa", version="0.1.0")


def data_dir() -> Path:
    """The directory holding the JSON bundles.

    Defaults to ``~/.local/share/glossa/data``. On the server the backend runs as root,
    so ``~`` is ``/root`` — which is exactly where ``cmd-push-data`` puts it, because it
    resolves the remote home of the user the backend actually runs as rather than the one
    it happens to SSH in as.
    """
    override = os.environ.get(DATA_DIR_ENV)
    root = Path(override).expanduser() if override else Path.home() / ".local" / "share" / "glossa"
    return root / DATA_ROUTE


def _mount_data() -> None:
    """Serve the data root, or serve nothing — but never take the platform down.

    enlace imports every app into ONE process. An exception escaping this module at import
    time does not break glossa; it fails the workers and 502s *every app on the platform*.
    A missing or unreadable data directory is a glossa problem and must stay one, so the
    OSError guard and ``check_dir=False`` are load-bearing, not defensive habit.
    """
    try:
        d = data_dir()
        d.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        print(f"[glossa] data dir unavailable ({e}); serving no data.", flush=True)
        return
    app.mount(
        f"/{DATA_ROUTE}",
        StaticFiles(directory=str(d), check_dir=False),
        name="data",
    )


@app.get("/health")
async def health() -> dict:
    """Report whether the data is actually there — the only way this app can be unwell."""
    d = data_dir()
    languages = d / "languages.json"
    return {
        "ok": languages.is_file(),
        "data_dir": str(d),
        "has_languages_index": languages.is_file(),
    }


try:
    _mount_data()
except OSError as e:  # e.g. an unreadable data root: never fatal to the platform
    print(f"[glossa] could not mount data dir ({e}); serving no data.", flush=True)
